<a href="https://colab.research.google.com/github/mrodriguezh23/Proteccion-De-Datos/blob/main/1_2_Comando_en_R.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Lenguaje R

### Miriam Rodríguez Hernández

### Protección de Datos

## Valores lógicos

In [ ]:
a <- TRUE
b <- FALSE

mode(a)
a

!a # negation

a && b # logical AND

a || b # logical OR

xor(a, b) # exclusive OR


[1] "logical"

[1] TRUE

[1] FALSE

[1] FALSE

[1] TRUE

[1] TRUE

 ## Álgebra booleana

In [ ]:
a <- c(TRUE,FALSE)
b <- c(TRUE,TRUE)

a
## [1] TRUE FALSE
b
## [1] TRUE TRUE
a & b # vectorized AND
## [1] TRUE FALSE
a | b # vectorized OR
## [1] TRUE TRUE
a && b # not vectorized
## [1] TRUE
a || b # not vectorized
## [1] TRUE


[1]  TRUE FALSE

[1] TRUE TRUE

[1]  TRUE FALSE

[1] TRUE TRUE

ERROR: ignored

## Operaciones en vectores

útil para manipular y comparar vectores de valores

In [ ]:
fruits <- c("apple", "pear", "orange", "lemon", "tangerine")
bakery <- c("bread", "buns", "cake", "cookies")
dairy <- c("milk", "butter", "cheese")
shopping <- c("bread", "butter", "apple", "cheese", "orange")

#intersecta los valores de los vectores fruits y shopping
intersect(fruits, shopping)
#intersecta los valores de los vectores bakery y shooping
intersect(bakery, shopping)
#intersecta los valores de los vectores dairy y shoopping
intersect(dairy, shopping)

#verifica si lemon es un valor en el vector dairy
"lemon" %in% dairy
#verifica si lemon es un valor en el vector fruits
"lemon" %in% fruits

#une los valores de bakery y dairy y al final regresa los valores que no están
#en el vector shopping
setdiff(union(bakery, dairy), shopping)

[1] "apple"  "orange"

[1] "bread"

[1] "butter" "cheese"

[1] FALSE

[1] TRUE

[1] "buns"    "cake"    "cookies" "milk"

## Valores character

Hay tres tipos de oraciones en el set de tipo character:

- doble comillas  "
- una comilla '
- comillas invertidas ´

In [ ]:
a <- "Él dijo 'hola' cuando entró"
a
#'Él dijo \'hola\' cuando entró'
b <- 'Él dijo "hola" cuando entró'
b
#'Él dijo "hola" cuando entró'

[1] "Él dijo 'hola' cuando entró"

[1] "Él dijo \"hola\" cuando entró"

## Manipulación de vectores

- **sort()** ordena los valores del vector.


- **rle()** 'run length encoding' longitud de la codificación cuenta el número de copias de cada valor.

In [ ]:
my.letters <- letters[c(1,5,10,3,1,4,21,1,10)]
my.letters
## [1] "a" "e" "j" "c" "a" "d" "u" "a" "j"
sort(my.letters)
## [1] "a" "a" "a" "c" "d" "e" "j" "j" "u"
rle(sort(my.letters))
## Run Length Encoding
## lengths: int [1:6] 3 1 1 1 2 1
## values : chr [1:6] "a" "c" "d" "e" "j" "u"

[1] "a" "e" "j" "c" "a" "d" "u" "a" "j"

[1] "a" "a" "a" "c" "d" "e" "j" "j" "u"

Run Length Encoding
  lengths: int [1:6] 3 1 1 1 2 1
  values : chr [1:6] "a" "c" "d" "e" "j" "u"

## Matrices y vectores multidimensionales

Los vectores tienen una sola dimensión, y obtenemos su longitud con el método length()

Las matrices tienen dos dimensiones y consultamos su dimensión con los métodos dim(), ncol() y nromw().

Los arreglos de R pueden tener cualquier número de dimensiones. Podemos consultar su dimensión con el método dim(). Y para consultar su clase están los métodos is.vector(), is.matrix() e is.array()

Se puede crear una nueva matriz con matrix() o as.matrix()


In [ ]:
A <- matrix(1:20, ncol = 4)

#imprime el valor de la primera columna y primera fila
A[1, 1]
#imprime los valores de la primera fila
A[1, ]
#imprime los valores de la primera columna
A[ , 1]
#Extraemo los valores de la segunda y tercer fila de la primer y tercer columna
A[2:3, c(1,3)]
#asigna numero 99 en posición tercer fila y cuarta columna
A[3, 4] <- 99
A
#se intercambian los valores de las posiciones señaladas
A[4:3, 2:1] <- A[3:4, 1:2]
A

[1] 1

[1]  1  6 11 16

[1] 1 2 3 4 5

[,1] [,2]
[1,] 2    12  
[2,] 3    13

[,1] [,2] [,3] [,4]
[1,] 1     6   11   16  
[2,] 2     7   12   17  
[3,] 3     8   13   99  
[4,] 4     9   14   19  
[5,] 5    10   15   20

[,1] [,2] [,3] [,4]
[1,] 1     6   11   16  
[2,] 2     7   12   17  
[3,] 9     4   13   99  
[4,] 8     3   14   19  
[5,] 5    10   15   20

## **Listas**

### - Extracción y subconjunto en una lista

In [ ]:
a.list <- list(x = 1:6, y = "a", z = c(TRUE, FALSE))
a.list

$x
[1] 1 2 3 4 5 6

$y
[1] "a"

$z
[1]  TRUE FALSE

a.list[["x"]] devuelve un vector numérico, mientras que a.list[1] una lista que contiene los valores numéricos de x.

a.list$x devuelve el mismo valor que a.list[["x"]], un vector numérico.

a.list[c(1,3)] devuelve la primer y tercer lista, mientras que a.list[[c(1,3)]] es un error.

In [ ]:
a.list$x
## [1] 1 2 3 4 5 6
a.list[["x"]]
## [1] 1 2 3 4 5 6
a.list[[1]]
## [1] 1 2 3 4 5 6
a.list["x"]
## $x
## [1] 1 2 3 4 5 6
a.list[1]
## $x
## [1] 1 2 3 4 5 6
a.list[c(1,3)]
## $x
## [1] 1 2 3 4 5 6
##
## $z
## [1] TRUE FALSE
try(a.list[[c(1,3)]])
## [1] 3

[1] 1 2 3 4 5 6

[1] 1 2 3 4 5 6

[1] 1 2 3 4 5 6

$x
[1] 1 2 3 4 5 6

$x
[1] 1 2 3 4 5 6

$x
[1] 1 2 3 4 5 6

$z
[1]  TRUE FALSE

[1] 3

### - Añadir y remover valores en una lista

- Para agregar usamos la función append()

- Para eliminar un valor de la lista le asignamos NULL

In [ ]:
another.list <- append(a.list, list(yy = 1:10, zz = letters[5:1]), 2L)
another.list

$x
[1] 1 2 3 4 5 6

$y
[1] "a"

$yy
 [1]  1  2  3  4  5  6  7  8  9 10

$zz
[1] "e" "d" "c" "b" "a"

$z
[1]  TRUE FALSE

In [ ]:
a.list$y <- NULL
a.list

$x
[1] 1 2 3 4 5 6

$z
[1]  TRUE FALSE

### -Listas anidadas

Una lista anidada puede ser construida dentro de una sola declaración en el cual, varias miembros de listas son creados.

In [ ]:
nested.list <- list(A = list("a", "aa", "aaa"), B = list("b", "bb"))
str(nested.list)

List of 2
 $ A:List of 3
  ..$ : chr "a"
  ..$ : chr "aa"
  ..$ : chr "aaa"
 $ B:List of 2
  ..$ : chr "b"
  ..$ : chr "bb"


## Operaciones con Data Frame

La función subset() filtra las filas. La condición es computada por cada fila y si devuele TRUE, la fila es incluida en el data frame, y excluida si devuelve FALSE.


In [ ]:
a.df <- data.frame(x = 1:6, y = "a", z = c(TRUE, FALSE))

subset(a.df, x > 3)

subset(a.df, x > 3)[ , -3]

subset(a.df, x > 3)$x


x y z    
4 4 a FALSE
5 5 a  TRUE
6 6 a FALSE

x y
4 4 a
5 5 a
6 6 a

[1] 4 5 6